### PR TITLE
Data creator

### PR DESCRIPTION
**Pull request by TylerLubeck**
I wanted to be able to quickly update only the variable dates. This script runs through the most recent year's worth of events and prompts for updates for any variable date holidays. 

The resulting CSV isn't as nicely formatted as the existing CSV. I'm not sure how important that is, so I've left it alone for now. I figure that's the kind of thing that requires a human touch to do properly, and can be done after the tool is run if it's desired.

This PR is the script and one example country. I'm happy to run it over the remaining countries if you'd like.

A run looks like this:
```
[git:<data_creator>] ~/Development/holidata.net/bin
➜ ./add-dates ../data/US.csv 2019
Variable Date Holiday Found
        en-US/ Birthday of Martin Luther King, Jr.
        es-US/ Cumpleaños de Martin Luther King, Jr.
Input a new date as MM-DD: 01-21

Variable Date Holiday Found
        en-US/ Washington's Birthday
        es-US/ Día del Presidente
Input a new date as MM-DD: 02-18

Variable Date Holiday Found
        en-US/MA Patriots' Day
        en-US/ME Patriots' Day
        es-US/MA Día del Patriota
        es-US/ME Día del Patriota
Input a new date as MM-DD: 04-15

Variable Date Holiday Found
        en-US/ Memorial Day
        es-US/ Día de los Caídos
Input a new date as MM-DD: 05-27

Variable Date Holiday Found
        en-US/ Labor Day
        es-US/ Día del Trabajo
Input a new date as MM-DD: 09-02

Variable Date Holiday Found
        en-US/ Columbus Day
        es-US/ Día de Columbus
Input a new date as MM-DD: 10-14

Variable Date Holiday Found
        en-US/ Veterans Day
        es-US/ Día de los Veteranos
Input a new date as MM-DD: 11-11

Variable Date Holiday Found
        en-US/ Thanksgiving Day
        es-US/ Día de Acción de Gracias
Input a new date as MM-DD: 11-28

```

### CODE REVIEW

**Comment by TylerLubeck** [comment]
I also don't know perl for squat - I hope it's ok to have done this in python

**Comment by TylerLubeck** [comment]
Hey @recollir @pbeckingham, any interest?

**Comment by tbabej** [comment]
@TylerLubeck this is not well publicized but we do have a tool that automates the holidata file generation (including variable holidays) - what we are missing is the country definitions:

https://github.com/GothenburgBitFactory/holidata/tree/master/python

**Comment by johanbove** [comment]
@tbabej What is the best way to provide the country definitions so we can complete the missing holiday data for 2019 and 2020?

**Comment by tbabej** [comment]
@johanbove The best way would be to provide a pull request to the repo, expanding the `countries.py` file:

https://github.com/GothenburgBitFactory/holidata/blob/master/python/countries.py

**Comment by lauft** [comment]
As @tbabej said, holiday definitions are now generated from the holidata project. See  https://github.com/GothenburgBitFactory/holidata/tree/master/python for more details.

**Pull request closed without merging**
